DROP TABLE IF EXISTS city;
CREATE TABLE city (
  ID         INT PRIMARY KEY AUTO_INCREMENT,
  NAME       VARCHAR(64),
  STATE      VARCHAR(32),
  COUNTRY    VARCHAR(8),
  UPDATED_AT DATETIME,
  CREATED_AT DATETIME
) DEFAULT CHARSET = utf8;
